### ISSUE TITLE
Orb crashes with: "wget: missing URL"

### ISSUE THREAD

**Issue by honzajavorek** [snyk/snyk-orb#21]
Hi, thanks for the CircleCI orb, it's quite useful! I'm using it on my OSS project for some time already, but in the past few days my nightly builds regularly fail with the following error:

```
#!/bin/bash -eo pipefail
if [[ ! -x "/usr/local/bin/snyk" ]]; then
  if [[ "linux" == "alpine" && "true" == "true" ]]; then
    apk add -q --no-progress --no-cache curl wget libstdc++ sudo
  fi
  curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" | grep linux | cut -d '"' -f 4 | xargs wget -q
  sha256sum -c snyk-linux.sha256
  sudo mv snyk-linux /usr/local/bin/snyk
  sudo chmod +x /usr/local/bin/snyk
fi
snyk config set disableSuggestions=true
snyk auth $SNYK_TOKEN

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

Exited with code exit status 123
```

For more details, see [the latest job](https://circleci.com/gh/honzajavorek/junior.guru/4266). When I wake up and rebuild the failed job, [it passes without problems](https://circleci.com/gh/honzajavorek/junior.guru/4269). What's going on? My configuration looks like this:

```yaml
version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
executors:
  python-js:
    docker:
      - image: circleci/python:3.7-node-browsers
    working_directory: ~/project
jobs:
  # needs $SNYK_TOKEN from https://app.snyk.io/account/
  security-scan:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: package.json
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: Pipfile
```

The full configuration is [here](https://raw.githubusercontent.com/honzajavorek/junior.guru/23c398d/.circleci/config.yml).
