### ISSUE TITLE
snyk/scan is not a valid type

### ISSUE THREAD

**Issue by GarethSharpe** [snyk/snyk-orb#25]
When attempting to run a Snyk scan as a step in my workflow, I am getting an invalid type error message due to some bad configuration when I am attempting to spin up an environment. I am 99% sure that this is a problem on my end, but I haven't been able to find it.

I have allowed uncertified orbs in my orb settings.

```
Build-agent version 1.0.38338-913686fd (xxx)

Configuration errors: 1 error occurred:

* In step 4 definition: step type "snyk/scan" is not a valid type
```

```
version: 2.1

orbs:
  snyk: snyk/snyk@0.0.10
  ...

jobs:
  ...
  snyk:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
          severity-threshold: high
          token-variable: SNYK_TOKEN
```

Does anyone have any thoughts? Cheers.
