### ISSUE TITLE
Cannot find a definition for command named snyk/scan-iac

### ISSUE THREAD

**Issue by rnsaway** [snyk/snyk-orb#64]
````
version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.1.0
  slack: circleci/slack@4.1
  snyk: snyk/snyk@1.1.2

jobs:
  test:
    executor: sam/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    steps:
      - checkout
      - snyk/scan-iac
````

Above is the relevant part of my circleci config.yml file.

Getting error "Cannot find a definition for command named snyk/scan-iac"

If i change it to just `- snyk/scan`, it works.
